name: Deploy to prod environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Setup Environment Variables
        run: |
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa_base64
          base64 -d ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh -tt ${{ secrets.SERVER_HOST }} echo "SSH connection works"

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          username: 'root'
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /var
            git clone git@github.com:ANIname/main-discord-bot.git
            cd main-discord-bot
            npm install
            npx tsc
            pm2 start npm --name "main-discord-bot" -- run start