name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy repository files
        env:
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SERVER_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$SERVER_HOST" >> ~/.ssh/known_hosts
          rsync -r $GITHUB_WORKSPACE/ root@SERVER_HOST:main-discord-bot

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          username: root
          script: |
            ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            rsync -r $GITHUB_WORKSPACE/ root@${{ secrets.SERVER_HOST }}:main-discord-bot
            cd main-discord-bot
            npm install
            npx tsc
            pm2 start npm --name "main-discord-bot" -- run start
