name: Deploy to prod environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          username: 'root'
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd main-discord-bot
            git pull
            npm install
            rm -rf dist
            npx tsc
            npx pm2 reload dist/src/index.js --name "main-discord-bot" || DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} MONGODB_URI=${{ secrets.MONGODB_URI }} npx pm2 start dist/src/index.js --name "main-discord-bot"