name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER_HOST }}'
          username: root
          key: '${{ secrets.SERVER_PASSWORD }}'
          script: |
            echo "Deploying to ${{ secrets.SERVER_HOST }}"
            rsync -r $GITHUB_WORKSPACE/ root@${{ secrets.SERVER_HOST }}:main-discord-bot
            cd main-discord-bot
            npm install
            npx tsc
            pm2 start npm --name "main-discord-bot" -- run start
