name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.prod.SERVER_HOST }}
          username: root
          key: ${{ secrets.prod.SERVER_PASSWORD }}
          script: |
            rsync -r $GITHUB_WORKSPACE/ root@${{ secrets.prod.SERVER_HOST }}:main-discord-bot
            cd main-discord-bot
            npm install
            npx tsc
            pm2 start npm --name "main-discord-bot" -- run start
